apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fnjoomlaopencart-db
  name: fnjoomlaopencart-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fnjoomlaopencart-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fnjoomlaopencart-db
    spec:
      securityContext:
        # because MySQL wants to CHOWN the directory, change the security context:
        # user 1000 = "user"
        # group 1000 = "user"
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - image: mysql
          name: fnjoomlaopencart-db
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fnjoomlaopencart-secret
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vol-claim-db
              # This volume claim claims a share also
              # used by other claims. So dedicate
              # a sub path inside that share.
              subPath: db-vol
      restartPolicy: Always
      volumes:
        - name: vol-claim-db
          persistentVolumeClaim:
            claimName: nfs-db-claim
