apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-db-claim
spec:
  storageClassName: manual
  # mount to this particular volume name (metadata.name)
  volumeName: vol-db
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
