apiVersion: v1
kind: ConfigMap
metadata:
  name: fnjoomlaopencart-configmap
data:
  # point to the DB service
  MYSQL_HOST: fnjoomlaopencart-db-service
  DB_NAME_JOOMLA: joomla
  DB_NAME_OPENCART: opencart
  DB_NAME_FISHNET: fishnet
