apiVersion: v1
kind: Service
metadata:
  labels:
    app: fnjoomlaopencart
  name: fnjoomlaopencart
spec:
  type: LoadBalancer
  externalIPs:
    - 192.168.1.169
    - 192.168.1.163
    - 192.168.1.141
  ports:
    - name: "80"
      port: 80
      targetPort: 80
      nodePort: 30003
  selector:
    app: fnjoomlaopencart
