apiVersion: v1
kind: PersistentVolume
metadata:
  # mount to this volume with "volumeName: vol-db"
  name: vol-db
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.144
    # It looks like you can mount to a path inside a share,
    # like /mnt/nfsdir/sub-path
    path: "/mnt/nfsdir"
